### ISSUE TITLE
鼠标滚轮操作在双显示屏的主屏幕上不起作用

### ISSUE THREAD

**Issue by Z-Clive** [XUJINKAI/OneQuick.AHK-legacy#1]
很方便的脚本！

有一个问题就是，有关鼠标滚轮的操作在双显示屏的主屏幕的边角上不起作用，比如音量，亮度啥的。

建议：右键右上角弹出的菜单里最好加入方便自己修改菜单的入口(比如打开那个文件什么的)

**Comment by XUJINKAI** [comment]
脚本对多显示屏是有支持的。
不过外接显示屏好像没法调亮度，我自己的surface屏幕可以，但外接的屏幕不行，应该是api的问题。
如果音量，翻页这些操作在某一个显示屏上完全没法用，请告诉我细节，比如是台式机还是笔记本，笔记本的话，笔记本屏幕是主屏幕还是第二屏幕，只用外接屏幕的时候能不能用等等。

添加右上角菜单的方法我再开一个issue回答。

**Comment by Z-Clive** [comment]
。。事实证明是和`Strokes Plus`有冲突，把其禁用就可以使用了
