### ISSUE TITLE
edge浏览器复制网址有时会卡死

### ISSUE THREAD

**Issue by XUJINKAI** [XUJINKAI/OneQuick.AHK-legacy#10]
疑似微软的锅...
也许和必应词典有关，看到的人请留言，发生卡死的时候必应词典有没有开。

**Comment by panxin8912** [comment]
一复制就卡死。我电脑没有bing词典，希望能解决。

**Comment by XUJINKAI** [comment]
@panxin8912 不是每次都卡死吧，我自己电脑出现的概率还挺小的。等win10 rs1出来看吧，希望这个是edge的问题....

**Comment by lijiayi** [comment]
每次都卡死，没有例外的。。。。win10 i7-7500

**Comment by XUJINKAI** [comment]
AHK版不再更新，新版已上架应用商店，感谢支持。
---
https://onequick.org/
微软应用商店搜索OneQuick即可获得
New Version available in Microsoft Store！
