### ISSUE TITLE
bug:左上角shift+[wheelup,wheeldown]亮度调节无法正常工作

### ISSUE THREAD

**Issue by sth4nothing** [XUJINKAI/OneQuick.AHK-legacy#13]
`shift+[wheelup,wheeldown]`均变暗

**Comment by XUJINKAI** [comment]
请问你的操作系统是？电脑是？

**Comment by sth4nothing** [comment]
**win10 build 14332 x64**  

>  我看了你的源代码后也感觉不应该发生，好奇怪。
> 问题没有复现，既然没有复现也差不多可以忽略吧。

**Comment by XUJINKAI** [comment]
没复现就先关issue了 XD
有其他问题欢迎提出 :)
