### ISSUE TITLE
跟新3.0后复制后不出现功能面板，复制记录也不显示了

### ISSUE THREAD

**Issue by JeyPiao** [XUJINKAI/OneQuick.AHK-legacy#14]
所有快捷键功能都失效了

**Comment by XUJINKAI** [comment]
删除feature.yaml再重启OneQuick行不行？
因为很多配置都移到feature.yaml中了，新版本没法读老版的配置。

**Comment by JeyPiao** [comment]
删除后，可以使用了 ^_^

**Comment by XUJINKAI** [comment]
新的配置文件里可以自由设置搜索网站和浏览器。
祝使用愉快~
