### ISSUE TITLE
虚拟桌面不能切换

### ISSUE THREAD

**Issue by njuzss** [XUJINKAI/OneQuick.AHK-legacy#15]
鼠标移到最下面，不能滚轮切换虚拟桌面

我用了双屏，跟这个有关系吗

另外 我将L-R改为L: ，B:改为R:  也不行 是怎么回事

**Comment by XUJINKAI** [comment]
在win10里，先创建多个虚拟桌面，切换快捷键才有效果。
OneQuick用的是win10的快捷键 ctrl+win+左箭头/右箭头，你可以自己测试一下。
双屏不影响。

请说一下具体是怎么改的，想要什么效果。还有改完得重启OneQuick才行。

**Comment by njuzss** [comment]
已有多个虚拟桌面，因为自己设置的是自动隐藏任务栏，所以害怕冲突，所以试着将B改为了R
重启了OneQuick，没有重启电脑

> R: 
>       wheelclick: "send #{tab}"
>       wheeldown: "send ^#{right}"
>       wheelup: "send ^#{left}"
>     L: 
>       ctrl_shift_wheeldown: "send {end}"
>       ctrl_shift_wheelup: "send {home}"
>       shift_wheeldown: "send {pgdn}{pgdn}{pgdn}{pgdn}{pgdn}"
>       shift_wheelup: "send {pgup}{pgup}{pgup}{pgup}{pgup}"
>       wheeldown: "send {pgdn}"
>       wheelup: "send {pgup}"

**Comment by njuzss** [comment]
另外，我改成了这样之后，在右侧滚到滚轮，会改变桌面图标的大小或者网页的大小
貌似作用变成了 Crtl+Up/Down 不知道这是怎么回事

**Comment by XUJINKAI** [comment]
配置应该没问题。
运行一下AHK/EnableUIAccess2AHK.ahk试试看？
其他的边缘操作没问题么？只有虚拟桌面有问题？如果直接按键盘ctrl+win+左/右呢？

**Comment by njuzss** [comment]
其他的边缘没有问题
直接用ctrl+win+左/右一直没问题的
运行过了，还是不行，我试着重启下电脑试试

**Comment by njuzss** [comment]
哈哈 还是不行呢 算了 直接键盘也是一样的

**Comment by XUJINKAI** [comment]
你可以试着直接编辑一下ext.ahk。就是右键菜单那个扩展ahk文件。
把下边代码加进去，如果这样还不行，就没办法了。

```
#if Sys.Cursor.IsPos("R")
WheelUp::send ^#{Left}
WheelDown::send ^#{Right}
#if
```

**Comment by XUJINKAI** [comment]
AHK版不再更新，新版已上架应用商店，感谢支持。
---
https://onequick.org/
微软应用商店搜索OneQuick即可获得
New Version available in Microsoft Store！
