### ISSUE TITLE
win10不能禁止开机程序启动通知

### ISSUE THREAD

**Issue by wiiwaker** [XUJINKAI/OneQuick.AHK-legacy#16]
如title，在设置里关闭掉onequick的通知后，在两三次重启后有几率通知会再次自动打开，在通知打开的情况下每次开机就会提示onequick已启动。

请问有办法能禁止提示onequick已启动，或者关闭onequick的通知后，能不自动打开吗？

**Comment by XUJINKAI** [comment]
指启动时右下角弹的tooltip么。
目前没有关闭通知的选项吧，想请问你在哪里找的设置。
我下个版本加一个对应的开关吧。

想现在手动关可以到core.ahk里，找Show_StartInfo函数，有一行

```
; 先弹tip再弹msgbox
Tray.Tip(msg)
```

把Tray.Tip(msg)删掉或者注释掉就行。

**Comment by wiiwaker** [comment]
多谢~

设置是win10的metro版设置，设置->系统->通知和操作->显示来自这些应用的通知，关闭通知就不会有tooltip，但有几率自动重置

**Comment by XUJINKAI** [comment]
我都没发现这个。。。赶紧研究一下 XD 感谢反馈

**Comment by szzhiyang** [comment]
@Emrys365 笔记本电脑都有自带屏幕亮度调节热键。

鼠标是万万不能代替键盘的。

**Comment by XUJINKAI** [comment]
AHK版不再更新，新版已上架应用商店，感谢支持。
---
https://onequick.org/
微软应用商店搜索OneQuick即可获得
New Version available in Microsoft Store！
