### ISSUE TITLE
如何在指定程序下屏蔽该应用

### ISSUE THREAD

**Issue by Travisss** [XUJINKAI/OneQuick.AHK-legacy#17]
请问如何在制定程序下屏蔽该应用，比如在cad中，屏蔽该程序。谢谢

**Comment by XUJINKAI** [comment]
目前还不能针对应用暂停，你可以左键点击托盘图标全局暂停

**Comment by XUJINKAI** [comment]
AHK版不再更新，新版已上架应用商店，感谢支持。
---
https://onequick.org/
微软应用商店搜索OneQuick即可获得
New Version available in Microsoft Store！
