### ISSUE TITLE
右键托盘某些设置会导致系统宕机

### ISSUE THREAD

**Issue by yws112358** [XUJINKAI/OneQuick.AHK-legacy#18]
我的win10 10240 
右击托盘的编辑自定义ahk必定导致系统宕机（画面卡住  至少5分钟 只好重启）
还有卸载autohotkey提示没有足够的系统权限无法卸载，准备尝试去installer文件夹用管理员权限卸载 程序与功能里是没办法

PS 后来在目录里的 ahk里用安装程序卸载了   请作者解决以上问题 谢谢

**Comment by XUJINKAI** [comment]
感谢反馈，为了让OneQuick对高权限程序起作用，安装的时候会修改ahk，导致普通方法卸载不掉。

请问托盘菜单的“配置功能”（feature.yaml）会卡住吗？
还有OneQuick目录有没有自动生成OneQuick.Ext.ahk文件。
