### ISSUE TITLE
切换虚拟桌面失效

### ISSUE THREAD

**Issue by ferris1993** [XUJINKAI/OneQuick.AHK-legacy#19]
有时候在使用时切换虚拟桌面会失效，另外跨桌面的复制粘贴有时也会失效，麻烦检查修改，这个小工具确实挺好使用的。

**Comment by XUJINKAI** [comment]
感谢反馈。如果概率比较小还随机出现，只能说是ahk自身的问题。复制粘贴可能是没复制上吧，按Ctrl shift x看看列表。以后争取让OneQuick更加稳定。

**Comment by XUJINKAI** [comment]
AHK版不再更新，新版已上架应用商店，感谢支持。
---
https://onequick.org/
微软应用商店搜索OneQuick即可获得
New Version available in Microsoft Store！
