### ISSUE TITLE
在word、qq等可输入面板时屏幕顶端滚轮快捷方式失效

### ISSUE THREAD

**Issue by CSkarsgard** [XUJINKAI/OneQuick.AHK-legacy#20]
不会切换tab而会变成键入一大堆tab

**Comment by XUJINKAI** [comment]
OneQuick是发送ctrl+tab和ctrl+shift+tab来切换标签页的。

试了一下word，直接按ctrl+tab确实会输入tab。word本来也没有标签页的功能，打开多个文档会在任务栏显示多个word，跟标签页没关系。ribbon菜单的切换可以按一下alt再按相应按键，但没有ctrl+tab切换这样的功能。

我电脑没有QQ。不过这两个问题应该一样。
这不是bug，即时没有OneQuick，在这些程序里，按ctrl+tab仍然会输入tab。

**Comment by jiangtiandao** [comment]
Try OfficeTab  @ShiinaGensho

**Comment by XUJINKAI** [comment]
请更新1.0
