### ISSUE TITLE
和synergy冲突。

### ISSUE THREAD

**Issue by Eyre5300** [XUJINKAI/OneQuick.AHK-legacy#21]
在synergy开启Server模式后，两者都开机自启后，OneQuick鼠标的快捷方式都不好用。
关闭synergy后，或者重新启动synergy后就好了

**Comment by XUJINKAI** [comment]
AHK版不再更新，新版已上架应用商店，感谢支持。
---
https://onequick.org/
微软应用商店搜索OneQuick即可获得
New Version available in Microsoft Store！
