### ISSUE TITLE
剪贴板快捷键冲突

### ISSUE THREAD

**Issue by OverflowCat** [XUJINKAI/OneQuick.AHK-legacy#22]
Office 里格式刷快捷键 (Ctrl + Shift + C) 不能用了。
[图片](http://mr23.xyz/Images/Github/OneQuickCtrlShiftC.png)

**Comment by XUJINKAI** [comment]
你可以编辑OneQuick的配置文件（feature.yaml）换掉冲突的快捷键；
或者使用office时点击托盘图标暂时禁用OneQuick。

熟悉ahk的话可以先删掉配置文件中`ctrl_shift_c: xClipboard.CopyAndShowMenu`这行，再去扩展文件（ext.ahk）里添加规则：

```
#if 规则
^+c::xClipboard.CopyAndShowMenu()
#if 
```

分应用屏蔽热键的功能以后有精力会添加到软件中。

**Comment by XUJINKAI** [comment]
#2
