### ISSUE TITLE
请问右上角鼠标滚轮切歌的事情

### ISSUE THREAD

**Issue by liupx17** [XUJINKAI/OneQuick.AHK-legacy#23]
右上角鼠标切歌太灵敏了，鼠标滚轮滚一下就切歌，能不能设置滚两下或者其他的

**Comment by XUJINKAI** [comment]
我在cmd和mobaxterm里测试都可以，你是哪个软件，更详细的信息？

**Comment by lizhihao6** [comment]
软件名字就是cmder～Window下很好用的一款终端
[cmder](http://cmder.net)

**Comment by XUJINKAI** [comment]
AHK版不再更新，新版已上架应用商店，感谢支持。
---
https://onequick.org/
微软应用商店搜索OneQuick即可获得
New Version available in Microsoft Store！
