### ISSUE TITLE
剪切板历史纪录能否有onedrive同步功能

### ISSUE THREAD

**Issue by quericy** [XUJINKAI/OneQuick.AHK-legacy#24]
折腾Ditto从V2搜索过来，发现几乎找不到带云盘同步功能的剪切板增强软件。

**Comment by XUJINKAI** [comment]
不太能。

剪贴板历史存在data/OneQuick.Data.PC_NAME.json文件中，这个文件在启动/退出程序的时候会自动读写，而且那个PC_NAME代表的是你的计算机名。

所以要同步的话，你只能是A电脑先不启动OneQuick，然后B电脑保存一堆记录以后重启一下OneQuick，然后等这个json文件同步过去后，再在电脑上启动OneQuick。（A电脑的OneQuick不能先启动，不然退出时又把json给覆盖了）

你还得修改https://github.com/XUJINKAI/OneQuick/blob/master/script/OneQuick.Core.ahk#L65 这行，把那个A_ComputerName改掉，让不同的电脑指到同一个文件。

所以。。。太麻烦了。。。还有个问题是这个json里保存的不仅仅是剪贴板记录。

不过感谢这个建议，我最近太忙，以后一定会完善OneQuick的。

ps 我不太确定用文件同步剪贴板记录能不能行，一是同步需要时间，二是onedrive同步完怎么通知到OneQuick，三是如上文中A电脑不能先启动OneQuick，不然A电脑就把json覆盖掉了。

**Comment by XUJINKAI** [comment]
#5 看一下能否解决

**Comment by XUJINKAI** [comment]
AHK版不再更新，新版已上架应用商店，感谢支持。
---
https://onequick.org/
微软应用商店搜索OneQuick即可获得
New Version available in Microsoft Store！
