### ISSUE TITLE
两个建议，一个是关于上面提到的切歌的问题，还有一个是网速显示的建议！

### ISSUE THREAD

**Issue by acenodie** [XUJINKAI/OneQuick.AHK-legacy#25]
#  两个建议，一个是关于上面提到的切歌的问题，还有一个是网速显示的建议！
1. 正如上面一个哥们提到的切歌太灵敏的问题，因为切歌并不是频繁的操作，为了避免误操作，可以把切歌的交互逻辑改为点击滚轮，呼出显示当前歌曲信息的小界面，如左边的音量图标一样，能让我们看到当前的歌曲的信息（当前歌曲名称和上下曲名称）和播放状态（暂停还是正在播放），如果鼠标继续停留在这个小界面上，那么滚轮的上下滚动就可以切歌了，如果离开这个界面，小界面自动隐藏，知道下次再右上角的位置按下滚轮！这样就能就能让我们防止误操作切歌，而且能对切歌所导致的结果（上下曲）更有预期！
2. 强烈希望在这个小插件上加上在任务栏显示实时网速的功能（这样也给你的图标常驻任务栏找到了合理的理由不是么，哈哈哈），因为我已经把这个程序设置为开机启动了（哈哈哈，可以把），而且也没有360悬浮窗那么高级的东西，所以强烈建议加上任务栏显示实时网速的功能，然后就可以把邮件的菜单加在这个上面了不是么！

**Comment by XUJINKAI** [comment]
感谢建议。
切歌的问题将来会想办法解决。
网速显示有些超过OneQuick的定位了，我会慎重考虑。

**Comment by XUJINKAI** [comment]
AHK版不再更新，新版已上架应用商店，感谢支持。
---
https://onequick.org/
微软应用商店搜索OneQuick即可获得
New Version available in Microsoft Store！
