### ISSUE TITLE
和office软件有冲突

### ISSUE THREAD

**Issue by Sev73n** [XUJINKAI/OneQuick.AHK-legacy#26]
截图了一下 大佬看看
![baidushurufa_2016-8-11_13-55-52](https://cloud.githubusercontent.com/assets/16495885/17579810/7a782af2-5fcb-11e6-91ea-62a437301398.png)

**Comment by XUJINKAI** [comment]
感谢反馈。
请问具体是在什么样的操作步骤下会出现？
另外AHK对剪贴板支持一般，偶尔会出现一些问题，可以先尝试重启OneQuick看看。

**Comment by wiiwaker** [comment]
这个问题我遇到过，但没找到准确复现的步骤。

而且当开启onequick后，复制html文本到excel里，更改不同的粘贴格式化选项会导致excel卡顿两三分钟。能否有选项彻底禁止剪贴板历史记录？现在即使把热键禁用了，还是会卡顿，除非退出onequick。

**Comment by XUJINKAI** [comment]
@wiiwaker 

https://github.com/XUJINKAI/OneQuick/blob/master/script/OneQuick.Core.ahk#L138
把这一行删掉或注释掉

然后修改配置文件clipboard.switch为0，把剪贴板功能彻底禁用。

如果还不行的话，再把这个OnClipboardChange 标签三行删掉，这样就不会监视剪贴板了
https://github.com/XUJINKAI/OneQuick/blob/master/script/OneQuick.Core.ahk#L992

AHK对剪贴板支持太弱，我甚至在考虑化繁为简只保留屏幕边缘功能了。

**Comment by wiiwaker** [comment]
感谢，把OneQuick.Core.ahk#L138注释掉和关闭剪贴板快捷键就ok了~

**Comment by XUJINKAI** [comment]
感谢，下个版本大约周一发，会修复这个问题。

**Comment by XUJINKAI** [comment]
AHK版不再更新，新版已上架应用商店，感谢支持。
---
https://onequick.org/
微软应用商店搜索OneQuick即可获得
New Version available in Microsoft Store！
