### ISSUE TITLE
如何调用OneQuick.Ext.ahk里的自定义函数？

### ISSUE THREAD

**Issue by lttlsnk** [XUJINKAI/OneQuick.AHK-legacy#27]
我在feature.yaml里添加了一行
win_`: OneQuick.User.wsl

然后在OneQuick.Ext.ahk里加上
`Ini()`
`{`
`this.Run := 1`
`OneQuick.Editor := "D:\ProgramFiles\VIM\vim74\gvim.exe -p --remote-tab-silent"`
`}`
`wsl()`
`{`
`if !WinExist("ahk_exe mintty.exe")`
`{`
`run d:\ProgramFiles\wsl-terminal\open-wsl.exe`
`wslshow = 1`
`}`
`else`
`{`
`if wslshow`
`{`
`WinExist("ahk_exe mintty.exe")`
`WinMinimize`
`wslshow = 0`
`}`
`else {`
`WinExist("ahk_exe mintty.exe")`
`WinRestore`
`WinActivate`
`wslshow = 1`
`}`
`}`
`return`
`}`

保存Reload, 按热键Win+`，提示不能运行命令OneQuick.User.wsl

**Comment by XUJINKAI** [comment]
不是OneQuick.User.wsl
是class_name.function_name
看wsl所在的class名字 class User_balabala
所以要运行的大概是User_balabala.wsl
嵌套的class同理

**Comment by lttlsnk** [comment]
呃，酱~

**Comment by BenjaminDbb** [comment]
OK, thank you. and I try again with ```Ctrl + C``` once. it works
I like this tool, convenient and powerful !
