### ISSUE TITLE
发现了使用中的两个问题

### ISSUE THREAD

**Issue by Chadwick97** [XUJINKAI/OneQuick.AHK-legacy#30]
1、在开启onequick的情况下，全屏游戏时鼠标移到右方或上方屏幕边界，很容易导致游戏跳出会到桌面。游戏并未停止，只是被切换回到桌面。这导致每次玩游戏之前我都要把它关掉
2、在问题1的背景下，玩游戏之前我把它暂时禁用快捷服务(程序依然挂着没停止)，之后再次开启会出现右键菜单空白的bug。经我测试，我开机启动onequick之后，禁用一次，再开启。有一定的几率，桌面右键菜单会变空白，鼠标指针移到空白处才显示，移到哪就显示哪一项

**Comment by XUJINKAI** [comment]
AHK版不再更新，新版已上架应用商店，感谢支持。
---
https://onequick.org/
微软应用商店搜索OneQuick即可获得
New Version available in Microsoft Store！
