### ISSUE TITLE
`#MaxThreadsPerHotkey, 20` 有什么特殊作用？

### ISSUE THREAD

**Issue by ipcjs** [XUJINKAI/OneQuick.AHK-legacy#32]
我看[文档](http://ahkcn.sourceforge.net/docs/commands/_MaxThreadsPerHotkey.htm)说，默认是1，用来防止重复按键。[这里](https://github.com/XUJINKAI/OneQuick/blob/master/script/OneQuick.Core.ahk#L31)设置成20有什么特殊作用吗？

**Comment by XUJINKAI** [comment]
AHK版不再更新，新版已上架应用商店，感谢支持。
---
https://onequick.org/
微软应用商店搜索OneQuick即可获得
New Version available in Microsoft Store！
