### ISSUE TITLE
无法启动，报错（见图），环境为Win7 64位

### ISSUE THREAD

**Issue by aben1188** [XUJINKAI/OneQuick.AHK-legacy#33]
解压后双击OneQuick Launcher.exe，报错：
![qq 20161109142021](https://cloud.githubusercontent.com/assets/9190887/20129077/3a952008-a688-11e6-9614-de6872199c9e.png)

**Comment by XUJINKAI** [comment]
AHK版不再更新，新版已上架应用商店，感谢支持。
---
https://onequick.org/
微软应用商店搜索OneQuick即可获得
New Version available in Microsoft Store！
