### ISSUE TITLE
左上角调节屏幕亮度遇到问题

### ISSUE THREAD

**Issue by sunthink** [XUJINKAI/OneQuick.AHK-legacy#35]
# 我用的是win10,onequick用的是3.1,左上角shift+滚轮调节亮度时，能调暗屏幕，但无法调亮

**Comment by XUJINKAI** [comment]
AHK版不再更新，新版已上架应用商店，感谢支持。
---
https://onequick.org/
微软应用商店搜索OneQuick即可获得
New Version available in Microsoft Store！
