### ISSUE TITLE
复制edge浏览器地址栏中的地址时卡死

### ISSUE THREAD

**Issue by Eyre5300** [XUJINKAI/OneQuick.AHK-legacy#36]
系统win10  版本 14393.447
在edge浏览器地址选中地址后，不论是按ctrl + c 还是鼠标右键后选择复制，都会跳出错误提示框，同时将浏览器卡死数秒钟。

**Comment by XUJINKAI** [comment]
#10 暂时没办法

**Comment by XUJINKAI** [comment]
AHK版不再更新，新版已上架应用商店，感谢支持。
---
https://onequick.org/
微软应用商店搜索OneQuick即可获得
New Version available in Microsoft Store！
