### ISSUE TITLE
托盘图标“褪色”

### ISSUE THREAD

**Issue by Licheng-Xu** [XUJINKAI/OneQuick.AHK-legacy#37]
![image_76](https://cloud.githubusercontent.com/assets/17547140/20456114/92ae2942-aea8-11e6-978f-3496f699e8ce.png)
图标有时候会“褪色”，但是不影响使用。
重启应用之后正常
![image_77](https://cloud.githubusercontent.com/assets/17547140/20456139/6d133f64-aea9-11e6-8ba8-1af6bd705f92.png)
想问问这是啥情况

**Comment by XUJINKAI** [comment]
我也经常遇到，感觉跟高分屏切换桌面有关

**Comment by XUJINKAI** [comment]
所以更不好做（囧  
我有罗技鼠标，知道这个的  
OneQuick的定位是热键工具，能在热键方面做到极致就非常好了，你之前那两个issue很棒！

**Comment by XUJINKAI** [comment]
AHK版不再更新，新版已上架应用商店，感谢支持。
---
https://onequick.org/
微软应用商店搜索OneQuick即可获得
New Version available in Microsoft Store！
