### ISSUE TITLE
鼠标移动到屏幕边缘没有触发相关功能，但剪切板等功能正常，这是为什么？

### ISSUE THREAD

**Issue by manning120008** [XUJINKAI/OneQuick.AHK-legacy#38]
鼠标移动到屏幕边缘没有触发相关功能，但剪切板等功能正常，这是为什么？
最新的win10.是因为广告插件的原因吗？还是系统的原因

**Comment by XUJINKAI** [comment]
是所有屏幕边缘的操作都不行么？
如果是音量音乐相关的，跟当前播放音乐的播放器有关，uwp的一般都可以。
如果是翻页，目标窗口得先激活。
你建立多个虚拟桌面试试用onequick切换看行不行。
最后，可以试试重启onequick。

**Comment by XUJINKAI** [comment]
AHK版不再更新，新版已上架应用商店，感谢支持。
---
https://onequick.org/
微软应用商店搜索OneQuick即可获得
New Version available in Microsoft Store！
