### ISSUE TITLE
玩lol的时候冲突太多

### ISSUE THREAD

**Issue by BHXGGGG** [XUJINKAI/OneQuick.AHK-legacy#39]
基本上切歌都不管用，右上角点击还会跳到桌面

**Comment by XUJINKAI** [comment]
右上角点击是因为你游戏是全屏模式，游戏独占所以会跳桌面。如果有全屏无边框模式的话就不会了。

OneQuick确实对游戏支持不好，如果冲突太多就玩的时候点托盘图标暂停吧。

**Comment by XUJINKAI** [comment]
AHK版不再更新，新版已上架应用商店，感谢支持。
---
https://onequick.org/
微软应用商店搜索OneQuick即可获得
New Version available in Microsoft Store！
