### ISSUE TITLE
反馈几个问题

### ISSUE THREAD

**Issue by kaishilinxi** [XUJINKAI/OneQuick.AHK-legacy#40]
首先是感谢作者公布本软件，
其次反馈一下本软件用的很爽，
再者本菜鸟希望以后能用的更爽，
最后来这里发帖提供一下个人意见。

一、已经有人反馈了，在玩全屏游戏(独占模式)的时候，比如LOL，点击屏幕边缘会使游戏弹出。
二、也已经有人反馈，但我不太清楚出现的原因，之后前后滚动滚轮后，会有各种“a”和“b”输出。
三、WIN10系统右键单机左上角其实有自带的功能，运行OneQuick后无法使用
四、这个软件非常喜欢，用起来也非常爽，但是随着使用，呼出栏越来越相形见绌，
    4.1 如果选中的内容很长，呼出栏宽度也会异常宽，影响美感，希望可分行，或减少显示的字符数。
    4.2 自定义快捷网址变多以后，呼出栏高度即将突破屏幕极限了，难道也要拆分两列么……或许可行
    4.3 常用快捷键不够用，希望添加双字母组合，比如 BD百度 BY百度云盘 BF百度翻译  BT百度贴吧
五、以下功能比较鸡肋，感觉可以取消
    5.1  希望(或允许用户)取消 右键单击右上角，功能鸡肋而且会使全屏游戏切出
    5.1  希望(或允许用户)取消 右键单击左上角，原因同上，主要原因是使得 win10自带的功能无效了
    5.1 shift+ctrl+c的呼出栏的 复制黏贴，系统自带的明显更实用（shift+ctrl+x的跳转作用也不大）
六、 shift+ctrl+v 的功能感觉shift+ctrl+c完全可以取代，所以可以把部分shift+ctrl+c功能搬运过去。
        shift+ctrl+Z/空格 也可以挖掘其他功能，好吧，收藏的快捷网址太多，呼出栏的显示空间不够用。
        哎，我的怨念，简直希望 shift+ctrl+c 除了快捷网址其他全没了
七、本人并不使用收藏夹功能，但对有用的人应该非常有潜力。
        这里有个小问题，收藏栏只能清空收藏夹，而不能删除某一条，(⊙o⊙)…

个人建议可以根据顺手程度，可以把 shift+ctrl+z/x/c/v 细化功能，比如
shift+ctrl+x 根据快捷键(a-b)，打开收藏夹里的网站，可扩展为打开某软件（刷黑则兼有复制功能）
shift+ctrl+c 根据快捷键(a-b&1-9)，搜索复制内容在指定网站的搜索          （刷黑则兼有复制功能）
shift+ctrl+v 根据快捷键(1-9)，选择指定剪切板的历史记录                         （自动替换复制的内容）
shift+ctrl+z 其他功能，比如打开哪一个浏览器什么的

![47maa 03jqjc 4 be nzvr](https://cloud.githubusercontent.com/assets/25947380/23202756/71e4128c-f91a-11e6-8301-542eca9a8289.png)

**Comment by XUJINKAI** [comment]
感谢反馈，非常详细。
考虑到我个人的时间安排，近期应该都不会有更新。
OneQuick目前遇到的问题，有一些奇怪的bug我自己也不知道原因，还有一些改进的建议由于ahk的局限，做起来很困难就搁置了。
未来我会重写OneQuick，不仅仅是因为有人喜欢，我自己也觉得它非常有前途。

关于反馈意见：
一、目前只能是进入游戏前点击托盘暂停OneQuick功能了。
二、这个就属于奇怪的bug，猜测和ahk的实现方式有关。
三、我也是win10系统，默认左上角右键有功能吗？
四、感谢这一条建议。
五、对于你不需要的功能，可以通过修改配置文件作修改或删除。右键托盘图标然后选择配置功能，删除【rclick: winmenu.show】这一行就不会显示窗口菜单了，其他同理。
六、同上，修改配置文件即可。另外，快捷键打开软件也可以通过修改配置实现，在hotkey、buildin里，后边的命令可以是cmd命令，当然也可以直接去写ahk脚本。
七、收藏夹内容可以删除单条，你的截图倒数第二个选项。这个功能目前藏的比较深，也是没有办法的办法。

**Comment by kaishilinxi** [comment]
三、我也是win10系统，默认左上角右键有功能吗？


好吧，这是我失误，应该是在默认桌面左下角，、
但是我习惯性吧菜单栏放于左边，所以触发的位置就在左上角了
（PS：开始栏顶端也是左上角，）

**Comment by XUJINKAI** [comment]
AHK版不再更新，新版已上架应用商店，感谢支持。
---
https://onequick.org/
微软应用商店搜索OneQuick即可获得
New Version available in Microsoft Store！
