### ISSUE TITLE
通过快捷键布局窗口？

### ISSUE THREAD

**Issue by YCF** [XUJINKAI/OneQuick.AHK-legacy#41]
不知道 windows 能不能直接控制窗口大小和位置？
我在 linux 下通过快捷键布局窗口。
我的代码：
https://gist.github.com/YCF/5a5da13669fb15e0bea25179ef4e72a3

**Comment by XUJINKAI** [comment]
windows有快捷键。。。
win+上下左右
alt+space
而且这个。。。和onequick好像没什么关系

**Comment by YCF** [comment]
你这个不是 ahk 吗？windows 的快捷键我试一下。

**Comment by XUJINKAI** [comment]
onequick是ahk实现的快捷键工具。。。但不是ahk
如果你是想让onequick增加这个功能的话，因为windows有快捷键，所以onequick不会增加这个feature

**Comment by llinfeng** [comment]
@YCF, 你说的部分功能有个叫 MaxTo的 可以解决。然后可以用下面的AHK脚本 重新载入（在切换 远程桌面的时候需要根据不同的显示器布局 重新载入）。

```
^!+m::
    process, exist, MaxTo.exe
    pid = %ErrorLevel%
    Process, Close, %pid%
    Sleep 1000
    run C:\Program Files\MaxTo\MaxTo.exe
return
```

**Comment by blqw** [comment]
我想启的是一个商店应用    microsoft to-do

暂时没找到怎么用命令启

**Comment by XUJINKAI** [comment]
@ddkk3000 你说的这个本质上就是环境变量，OneQuick不能做什么吧。
如果你指的不是在cmd里运行，而只是启动程序的话，那现在也做得到，自定义热键选运行命令就行了。
