### ISSUE TITLE
切换虚拟桌面失效

### ISSUE THREAD

**Issue by LANTERNLALA** [XUJINKAI/OneQuick.AHK-legacy#42]
有时候会变成切歌，但这时候不能用中键暂停。
有时候会变成放大或缩小桌面图标。

**Comment by LANTERNLALA** [comment]
试着把播放器的快捷键去掉之后发现不会变成切歌了，但还是无法切换桌面

**Comment by LANTERNLALA** [comment]
好奇怪，我发现只有当第二个桌面打开了某一个特定的软件切换功能才有用。。。

**Comment by XUJINKAI** [comment]
首先你得打开至少两个虚拟桌面。然后试试在重启以后的状态（或者所有软件都关闭的情况下）能不能用。
如果通过OneQuick不行，那window内置的ctrl+win+左/右能不能切换。
OneQuick做的仅仅是调用系统API，有时会因为不同的系统安装的软件不同发生一些奇怪的事情。

**Comment by Jray616** [comment]
同样是虚拟桌面切换没反应，windows自带的切换快捷键能够使用。

**Comment by zhengyu** [comment]
我升级到最新版的autohotkey就没问题了

**Comment by blqw** [comment]
可以了

**Comment by XUJINKAI** [comment]
AHK版不再更新，新版已上架应用商店，感谢支持。
---
https://onequick.org/
微软应用商店搜索OneQuick即可获得
New Version available in Microsoft Store！
