### ISSUE TITLE
左上调音量的时候能否隐藏音量条的显示？

### ISSUE THREAD

**Issue by fenglingyu** [XUJINKAI/OneQuick.AHK-legacy#43]
感觉不太想看到这个视觉提示。能否设置关掉？

**Comment by XUJINKAI** [comment]
你可以修改配置文件
wheeldown: "Send {volume_down}"
wheelup: "Send {volume_up}"

换成
wheeldown: "Sys.Volume.Down"
wheelup: "Sys.Volume.Up"

**Comment by fenglingyu** [comment]
非常感谢！




在 2017-03-27 14:32:43，"XJK" <notifications@github.com> 写道：


你可以修改配置文件
wheeldown: "Send {volume_down}"
wheelup: "Send {volume_up}"

换成
wheeldown: "Sys.Volume.Down"
wheelup: "Sys.Volume.Up"
