### ISSUE TITLE
excel剪切板被占用问题有解决方案吗？

### ISSUE THREAD

**Issue by HKB01** [XUJINKAI/OneQuick.AHK-legacy#44]
如题，麻烦知道的回答一下。谢谢。

**Comment by XUJINKAI** [comment]
没遇到过，可以具体讲一下如何出现的吗？
你可以尝试重启OneQuick看看。

**Comment by HKB01** [comment]
系统环境：win10，office2013
就是在excel里拖拽单元格时，会提示“无法释放剪切板空间……”，而且只要退出onequick就不会。

**Comment by XUJINKAI** [comment]
我是2016。我试了一下确实出现了这个问题，但两次之后就再也没法复现了。而且不影响拖拽操作。
OneQuick的剪贴板用的就是AHK自带的函数，这个问题暂时不在我的能力范围内。
如果提示太频繁的话，重启onequick也没用的话，确实得暂时关闭onequick了。

**Comment by HKB01** [comment]
好的，谢谢

**Comment by XUJINKAI** [comment]
AHK版不再更新，新版已上架应用商店，感谢支持。
---
https://onequick.org/
微软应用商店搜索OneQuick即可获得
New Version available in Microsoft Store！
