### ISSUE TITLE
win10系统，节电模式下，左上角调节亮度均为调暗

### ISSUE THREAD

**Issue by fxy147** [XUJINKAI/OneQuick.AHK-legacy#46]
win10系统，一般情况下调节亮度没有问题，当打开系统的节电模式时，无论调亮还是调暗，亮度均变暗。

**Comment by XUJINKAI** [comment]
AHK版不再更新，新版已上架应用商店，感谢支持。
---
https://onequick.org/
微软应用商店搜索OneQuick即可获得
New Version available in Microsoft Store！
