### ISSUE TITLE
网页视频问题

### ISSUE THREAD

**Issue by nameease** [XUJINKAI/OneQuick.AHK-legacy#47]
在一些网页上播放视频的时候，在左上角滚轮调节音量，会导致视频卡住无法播放，刷新后才能继续播放。顺便问问，作者有没有各种功能的完整使用介绍呀~

**Comment by XUJINKAI** [comment]
AHK版不再更新，新版已上架应用商店，感谢支持。
---
https://onequick.org/
微软应用商店搜索OneQuick即可获得
New Version available in Microsoft Store！
