### ISSUE TITLE
使用UWP版本bilibili打开av号

### ISSUE THREAD

**Issue by XUJINKAI** [XUJINKAI/OneQuick.AHK-legacy#48]
打开[OneQuick.Core.ahk](https://github.com/XUJINKAI/OneQuick/blob/master/script/OneQuick.Core.ahk#L2650)文件，
搜索并将 `run("http://www.bilibili.com/video/av" avn1)`
这行替换为 `run("bilibili://video/" avn1)`

**Comment by THRILLERLEMON** [comment]
OneQuick快捷键拟删除。（显示界面、禁用服务）
这个功能挺好的吧，有的时候打游戏打一半想起来onequick没关，然后直接用快捷键关了，还不用切游戏
