### ISSUE TITLE
win10开机启动失败

### ISSUE THREAD

**Issue by wm13282041** [XUJINKAI/OneQuick.AHK-legacy#49]
首先，感谢作者开发如此好用的软件
描述一下问题:
最初使用是可以开机启动的，重装系统后以及平板上都不能正常开机启动,软件自身选项以及管理软件都显示启动项开启了,系统：win10 x64 pro 1703
希望作者或者有大神指点一下，万分感谢。

**Comment by XUJINKAI** [comment]
AHK版不再更新，新版已上架应用商店，感谢支持。
---
https://onequick.org/
微软应用商店搜索OneQuick即可获得
New Version available in Microsoft Store！
