### ISSUE TITLE
能否建一个qq或电报群呢，方便反馈

### ISSUE THREAD

**Issue by komazhou** [XUJINKAI/OneQuick.AHK-legacy#50]
能否建一个qq或电报群呢，方便反馈

**Comment by XUJINKAI** [comment]
感谢你的建议。
因为一些个人原因，OneQuick停止更新了很久。
我最近在考虑开发新版本的事情，到时相关的宣传和联络方式也会跟上。

**Comment by komazhou** [comment]
哦，谢谢你的回复，不过有一个个人需求，不知道如何实现，选中一段话之后，按Ctrl+shift+c之后，增加一个选项，复制该段话的内容，新建一个emeditor窗口，激活该窗口，将复制的那段话粘贴到emeditor窗口中，
我看了一遍里面的ahk文件内容，发现操作列表是不是用menu.add来增加的，不知道能否帮我实现一下，谢谢

**Comment by komazhou** [comment]
刚刚在帮助里面找到了run_user() 函数，直接在里面写了一个脚本，利用里面的执行实现了，不知道还有没有增加操作列表项的方法实现；
另外，我现在只是依葫芦画瓢写的一个脚本，不知道能否帮我优化一下，检测当前是否已经打开了新建的空白emeditor，如果有，那么激活它，我使用IfWinExist这个命令的时候，不知道后面的窗口类怎么获取，
现在我写的脚本：
run_user(command)
{
Send ^c
Run D:\Program Files (Portable)\EmEditor\EmEditor.exe
WinActivate
Sleep 1000
Send ^v
}

**Comment by XUJINKAI** [comment]
官网可以找到discord群的信息。
---
AHK版已停止更新，请使用新版 https://onequick.org/
微软应用商店搜索OneQuick即可获得
New Version available in Microsoft Store！
