### ISSUE TITLE
stopped working

### ISSUE THREAD

**Issue by leox23** [XUJINKAI/OneQuick.AHK-legacy#51]
every day he used it, last week stopped working, already i've tried everything and I failed to work, I'm in Windows 8.1, this is the dialog box that I, you know to that should be?

![imagen](https://user-images.githubusercontent.com/21028236/28508569-c6171960-7009-11e7-8be1-7fcf8df9918f.png)

then I give ok, you try to install, but it appears right away again.

try older versions of these files, even download the original version again, and the same message appears

**Comment by XUJINKAI** [comment]
AHK版已停止更新，请使用新版 https://onequick.org/
微软应用商店搜索OneQuick即可获得
New Version available in Microsoft Store！
