### ISSUE TITLE
底端滚轮按键与系统自带新建窗口冲突

### ISSUE THREAD

**Issue by kenkangxgwe** [XUJINKAI/OneQuick.AHK-legacy#52]
在任务栏上点击鼠标中间，比如在资源管理器下方，会新建一个资源管理器窗口，这会与OneQuick触发的`#{tab}`功能冲突。不知是否有方法可以在`OneQuick.feature.yaml`中禁用掉这个功能。谢谢！

**Comment by XUJINKAI** [comment]
找`wheelclick: "send #{tab}"`这行删掉就行

**Comment by kenkangxgwe** [comment]
谢谢！用`#`注释掉也可以。
