### ISSUE TITLE
打开Excel和标签同时，复制标签上文字会出问题

### ISSUE THREAD

**Issue by chang987654** [XUJINKAI/OneQuick.AHK-legacy#53]
![_20170929103731](https://user-images.githubusercontent.com/32379418/30998661-e70dd6bc-a502-11e7-8795-616b49b1c423.png)

**Comment by XUJINKAI** [comment]
快捷键启动一个全屏的界面？
我看不到这样做有什么好处，本来OneQuick的特点就是不遮挡当前桌面+盲操作。
你可以直接说说你想解决哪些问题？

**Comment by nuoicom** [comment]
> 快捷键启动一个全屏的界面？
> 我看不到这样做有什么好处，本来OneQuick的特点就是不遮挡当前桌面+盲操作。
> 你可以直接说说你想解决哪些问题？

就以目前版本来说，一般有些窗口全屏化（不是独占那种）快捷键就会被挡住，这时候就需要启动一下win键（但是中键不能用，会按进那个窗口），我的方法就是启动一个类似mac的Launchpad窗口来按中键。本质上是也许就是想解决一些遮挡问题？😵

**Comment by XUJINKAI** [comment]
AHK版已停止更新，请使用新版 https://onequick.org/
微软应用商店搜索OneQuick即可获得
New Version available in Microsoft Store！
