### ISSUE TITLE
2个问题

### ISSUE THREAD

**Issue by blqw** [XUJINKAI/OneQuick.AHK-legacy#55]
1, 管理员模式运行的窗口激活时 所有鼠标功能无法使用
2, 在excel2016中  滚动滚轮 调整音量  内容也会跟着滚

**Comment by XUJINKAI** [comment]
ahk版已停止更新，请使用WPF版本。
若是WPF版的问题，第一个问题无解，官网有介绍，目前系统限制。
https://onequick.org/feedback

**Comment by blqw** [comment]
兄弟我花钱买了专业的    WPF有专业版不   另外设置怎么导出来

**Comment by XUJINKAI** [comment]
AHK版没有付费版。WPF的专业版要去应用商店下载然后内购开启。
AHK版的设置没法自动导入WPF版，只能手动添加。
