### ISSUE TITLE
[建议]新版本加入禁用屏幕角右键菜单功能 - 干扰全屏游戏

### ISSUE THREAD

**Issue by usernamejim12** [XUJINKAI/OneQuick.AHK-legacy#56]
如题。如以包含此功能，麻烦指点下方法。
非常感谢大佬开发的应用。
非常方便，不过因为打排位赛鼠标经常会跑到屏幕角，偶然跳菜单干扰甚大，不得不先停用了。

**Comment by XUJINKAI** [comment]
AHK版已停止更新，请升级新版 https://onequick.org/
微软应用商店搜索OneQuick即可
