### ISSUE TITLE
win10 操作表格复制粘贴后提示NET FRAME 崩溃

### ISSUE THREAD

**Issue by welaing** [XUJINKAI/OneQuick.AHK-legacy#58]
在win10平台操作表格内复制粘贴时，会提示NET Framework崩溃，之后的复制粘贴失效。

**Comment by XUJINKAI** [comment]
AHK版已停止更新。
如果是WPF版的问题，请到这里提issue： https://github.com/OneQuick/OneQuick.net/issues
另外我需要更详细的信息，参考 https://onequick.org/support/ 如果能稳定复现并提供方法就更好了
