### ISSUE TITLE
某些场景下，左上角调节音量会输出字母b和c

### ISSUE THREAD

**Issue by XUJINKAI** [XUJINKAI/OneQuick.AHK-legacy#8]
远程桌面时会出现，小娜中疑似会出现，暂不明原理

**Comment by LeonDong1993** [comment]
我也遇到了这个问题。。。。

**Comment by LeonDong1993** [comment]
我测试了一下，这个问题貌似是和输入法的兼容性问题，为了彻底解决，还是吧音量接口换成soundset吧
在run里面再写一个regexmatch
if(RegExMatch(command, "i)SoundSet (.*)", sd))
{
            SoundSet %sd1%
            return
}

然后再yaml文件里面定义成 
wheelup: "SoundSet +2"

即可解决问题

**Comment by LeonDong1993** [comment]
比较尴尬的是，看不见音量动态调整的条子了。。。。。

**Comment by XUJINKAI** [comment]
@LeonDong1993 是的 其实soundset的函数我也写了 可是为了那个条子。。。

**Comment by XUJINKAI** [comment]
而且那个条子是win10自带的 快速降低音量的时候还有个加速度。。。
所以这个问题我暂时就这么放着了 以后还是想在保留这个音量条的情况下解决 左上角滚轮出音量条也算是OneQuick的标志性功能了

**Comment by LeonDong1993** [comment]
@XUJINKAI 是的，这个想法创意实在太棒了，非常标志性的功能，很方便，非常感谢~ 边缘操作实在很方便，我现在还加入了 ctrl+tab系列的切标签支持， 这样QQ 搜狗浏览器也可以切换标签了！！

**Comment by XUJINKAI** [comment]
@LeonDong1993 切换标签页的话 上边缘滚轮不就是么

**Comment by LeonDong1993** [comment]
@XUJINKAI 自己傻逼了，yaml配置文件被自己改坏了，没有调用你写的prebtab和nexttab接口， 嘿嘿 现在改回去了，可以两者 都兼容了。。。

**Comment by XUJINKAI** [comment]
AHK版不再更新，新版已上架应用商店，感谢支持。
---
https://onequick.org/
微软应用商店搜索OneQuick即可获得
New Version available in Microsoft Store！
